name: Rust

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check format
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --release

    - name: Test
      run: |
        cargo build
        cargo test

# vim: set sw=2 ts=2 sts=2:
